<?php

global $alphabet;
$alphabet = array(
    '1' =>'a',
    '2' => 'b',
    '3' => 'c',
    '4' => 'd',
    '5' => 'e',
    '6' => 'f',
    '7' => 'g',
    '8' => 'h',
    '9' => 'i',
    '10' => 'j',
    '11' => 'k',
    '12' => 'l',
    '13' => 'm',
    '14' => 'n',
    '15' => 'o',
    '16' => 'p',
    '17' => 'q',
    '18' => 'r',
    '19' => 's',
    '20' => 't',
    '21' => 'u',
    '22' => 'v',
    '23' => 'w',
    '24' => 'x',
    '25' => 'y',
    '26' => 'z',
);

function shift_cipher_menu() {
    $items['shift_cipher'] = array(
        'title' => t('Shift Cipher'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_form'),
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );

    // $items['shift_cipher_results_page'] = array(
    //     'title' => t('Shift Cipher Results'),
    //     'page callback' => 'shift_cipher_results',
    //     // 'page arguments' => array('shift_cipher_english_form' 'shift_cipher_results'),
    //     'access callback' => TRUE,
    //     'type' => MENU_CALLBACK,
    // );

    $items['shift_cipher_results_page'] = array(
        'title' => t('Shift Cipher to English Results'),
        'page callback' => 'drupal_get_form',
        'page arguments' => array('shift_cipher_english_form'),
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items['shift_cipher_english_results_page'] = array(
        'title' => t('Shift Cipher Results'),
        'page callback' => 'shift_cipher_english_results',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    return $items;
}
// MODULE FORM
function shift_cipher_form() {
    $form['shift_value'] = array(
        '#title' => t('Shift Value'),
        '#description' => t('Please enter how many spots you would like to shift each letter.'),
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_integer_positive', 'element_validate_shift_range'),
        '#required' => TRUE,
    );

    $form['shift_direction'] = array(
        '#title' => t('Shift Direction'),
        '#description' => t('Please enter the direction you would like to shift your letters.'),
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );

    $form['phrase'] = array(
        '#title' => t('Phrase'),
        '#description' => t('Enter the phrase you would like encrypted.'),
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );

    return $form;
}

function shift_cipher_english_form() {
    $form['encript_results'] = array(
        '#markup' => '<p class="encripted_results">Encrypted Phrase: <strong>' . $_SESSION['encryption'] . '</strong></p>',
    );

    $form['return_shift_value'] = array(
        '#title' => t('Return to English Shift Value'),
        '#description' => t('Please enter how many spots you would like to shift each letter.'),
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_integer_positive', 'element_validate_shift_range'),
        '#required' => TRUE,
    );

    $form['return_shift_direction'] = array(
        '#title' => t('Return to English Shift Direction'),
        '#description' => t('Please enter the direction you would like to shift your letters.'),
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_direction'),
        '#required' => TRUE,
    );

    $form['encrypted_phrase'] = array(
        '#title' => t('Encrypted Phrase to Return to English'),
        '#description' => t('Enter the phrase you would like to return to english.'),
        '#type' => 'textfield',
        '#element_validate' => array('element_validate_phrase'),
        '#required' => TRUE,
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Encrypt!',
    );

    return $form;
}

// VALIDATION
function element_validate_shift_range($element) {
    if($element['#value'] > 25) {
        form_error($element, t('Please enter a positive number less than 25. Anything over that is redundant.'));
    }
}

function element_validate_direction($element) {
    $lower_case_element = strtolower($element['#value']);

    if($lower_case_element !== 'left' && $lower_case_element !== 'right') {
        form_error($element, t('Please enter either "left" or "right" for the shift direction.'));
    }
}

function element_validate_phrase($element) {
    if(!preg_match('/^[a-zA-Z .\?!]+$/i', $element['#value'])) {
        form_error($element, t('Please enter a phrase using only letters and punctuation. ("." or "," or "!" or "?")'));
    }
}
// FORM PROCESSING
function shift_cipher_form_submit($form, &$form_state) {
    global $alphabet;
    $phrase = strtolower($form_state['values']['phrase']);
    $split_phrase = str_split($phrase);
    $shift = $form_state['values']['shift_value'];
    $shift_multiplier = $shift / 26;
    $direction = strtolower($form_state['values']['shift_direction']);
    $encrypted_phrase = array();

    if($shift_multiplier < 1) {
        $shift_multiplier = 1;
    } else {
        $shift_multiplier = floor($shift_multiplier);
    }

    foreach($split_phrase as $letter) {
        if(in_array($letter, $alphabet)) {
            if($direction === 'right') {
                $letter_key = array_search($letter, $alphabet) + $shift;
                if($letter_key > 26) {
                    $letter_key = $letter_key - (26 * $shift_multiplier);
                }
                array_push($encrypted_phrase, $alphabet[$letter_key]);
            }

            if($direction === 'left') {
                $letter_key = array_search($letter, $alphabet) - $shift;
                if($letter_key < 1) {
                    $letter_key = $letter_key + (26 * $shift_multiplier);
                }
                array_push($encrypted_phrase, $alphabet[$letter_key]);
            }
        } else {
            array_push($encrypted_phrase, $letter);
        }
    }

    $results = implode('', $encrypted_phrase);
    $_SESSION['encryption'] = $results;
    $form_state['redirect'] = 'shift_cipher_results_page';
}

function shift_cipher_english_form_submit($form, &$form_state) {
    global $alphabet;
    $encrypted_phrase = strtolower($form_state['values']['encrypted_phrase']);
    $split_encrypted_phrase = str_split($encrypted_phrase);
    $return_shift = $form_state['values']['return_shift_value'];
    $return_direction = strtolower($form_state['values']['return_shift_direction']);
    $english_phrase = array();

    foreach($split_encrypted_phrase as $letter) {
        if(in_array($letter, $alphabet)) {
            if($return_direction === 'right') {
                $letter_key = array_search($letter, $alphabet) + $return_shift;
                if($letter_key > 26) {
                    $letter_key = $letter_key - 26;
                }
                array_push($english_phrase, $alphabet[$letter_key]);
            }

            if($return_direction === 'left') {
                $letter_key = array_search($letter, $alphabet) - $return_shift;
                if($letter_key < 1) {
                    $letter_key = $letter_key + 26;
                }
                array_push($english_phrase, $alphabet[$letter_key]);
            }
        } else {
            array_push($english_phrase, $letter);
        }
    }

    $english_results = implode('', $english_phrase);
    $_SESSION['encrypted_phrase'] = $encrypted_phrase;
    $_SESSION['english'] = $english_results;
    $form_state['redirect'] = 'shift_cipher_english_results_page';
}

// RESULTS DISPLAY
// function shift_cipher_results() {
//     return '<p>Encrypted Phrase: ' . $_SESSION['encryption'] . '</p>';
// }

function shift_cipher_english_results() {
    return '<p>You changed <strong>' . $_SESSION['encrypted_phrase'] . '</strong> back to <strong>' . $_SESSION['english'] . '</strong></p>';
}
